# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/commercial_activities
    username: postgres
    password: admin

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjA3NjQwMWYwNTQzNWVlNjFlMTUxZDcyOTEyZWU3ZDhjOTQxYmY4Y2Q3NzU2ZjgyYWJjYmIzYmU2YzYwZTEwMGViNTNhYTM3MjhlOWIxNjhiZjY5MzMxNTM3MTJkMzlmMWY3NjJmYjBhNGNlZDNlYjVhMzQxOTc1YmVjNjJlZmU=
