package com.commercial.activities.domain;

import static com.commercial.activities.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CashCollectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashCollectionAllPropertiesEquals(CashCollection expected, CashCollection actual) {
        assertCashCollectionAutoGeneratedPropertiesEquals(expected, actual);
        assertCashCollectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashCollectionAllUpdatablePropertiesEquals(CashCollection expected, CashCollection actual) {
        assertCashCollectionUpdatableFieldsEquals(expected, actual);
        assertCashCollectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashCollectionAutoGeneratedPropertiesEquals(CashCollection expected, CashCollection actual) {
        assertThat(actual)
            .as("Verify CashCollection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashCollectionUpdatableFieldsEquals(CashCollection expected, CashCollection actual) {
        assertThat(actual)
            .as("Verify CashCollection relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashCollectionUpdatableRelationshipsEquals(CashCollection expected, CashCollection actual) {
        assertThat(actual)
            .as("Verify CashCollection relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
