package com.commercial.activities.domain;

import static com.commercial.activities.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CashDisbursementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashDisbursementAllPropertiesEquals(CashDisbursement expected, CashDisbursement actual) {
        assertCashDisbursementAutoGeneratedPropertiesEquals(expected, actual);
        assertCashDisbursementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashDisbursementAllUpdatablePropertiesEquals(CashDisbursement expected, CashDisbursement actual) {
        assertCashDisbursementUpdatableFieldsEquals(expected, actual);
        assertCashDisbursementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashDisbursementAutoGeneratedPropertiesEquals(CashDisbursement expected, CashDisbursement actual) {
        assertThat(actual)
            .as("Verify CashDisbursement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashDisbursementUpdatableFieldsEquals(CashDisbursement expected, CashDisbursement actual) {
        assertThat(actual)
            .as("Verify CashDisbursement relevant properties")
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashDisbursementUpdatableRelationshipsEquals(CashDisbursement expected, CashDisbursement actual) {
        assertThat(actual)
            .as("Verify CashDisbursement relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
