package com.commercial.activities.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompanySubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionAllPropertiesEquals(CompanySubscription expected, CompanySubscription actual) {
        assertCompanySubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertCompanySubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionAllUpdatablePropertiesEquals(CompanySubscription expected, CompanySubscription actual) {
        assertCompanySubscriptionUpdatableFieldsEquals(expected, actual);
        assertCompanySubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionAutoGeneratedPropertiesEquals(CompanySubscription expected, CompanySubscription actual) {
        assertThat(actual)
            .as("Verify CompanySubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionUpdatableFieldsEquals(CompanySubscription expected, CompanySubscription actual) {
        assertThat(actual)
            .as("Verify CompanySubscription relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanySubscriptionUpdatableRelationshipsEquals(CompanySubscription expected, CompanySubscription actual) {
        assertThat(actual)
            .as("Verify CompanySubscription relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
