package com.commercial.activities.domain;

import static com.commercial.activities.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DebtPaymentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtPaymentAllPropertiesEquals(DebtPayment expected, DebtPayment actual) {
        assertDebtPaymentAutoGeneratedPropertiesEquals(expected, actual);
        assertDebtPaymentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtPaymentAllUpdatablePropertiesEquals(DebtPayment expected, DebtPayment actual) {
        assertDebtPaymentUpdatableFieldsEquals(expected, actual);
        assertDebtPaymentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtPaymentAutoGeneratedPropertiesEquals(DebtPayment expected, DebtPayment actual) {
        assertThat(actual)
            .as("Verify DebtPayment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtPaymentUpdatableFieldsEquals(DebtPayment expected, DebtPayment actual) {
        assertThat(actual)
            .as("Verify DebtPayment relevant properties")
            .satisfies(a ->
                assertThat(a.getAmountPaid())
                    .as("check amountPaid")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountPaid())
            )
            .satisfies(a ->
                assertThat(a.getRemainingAmount())
                    .as("check remainingAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRemainingAmount())
            )
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtPaymentUpdatableRelationshipsEquals(DebtPayment expected, DebtPayment actual) {
        assertThat(actual)
            .as("Verify DebtPayment relationships")
            .satisfies(a -> assertThat(a.getDebt()).as("check debt").isEqualTo(expected.getDebt()));
    }
}
