package com.commercial.activities.domain;

import static com.commercial.activities.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DebtAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtAllPropertiesEquals(Debt expected, Debt actual) {
        assertDebtAutoGeneratedPropertiesEquals(expected, actual);
        assertDebtAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtAllUpdatablePropertiesEquals(Debt expected, Debt actual) {
        assertDebtUpdatableFieldsEquals(expected, actual);
        assertDebtUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtAutoGeneratedPropertiesEquals(Debt expected, Debt actual) {
        assertThat(actual)
            .as("Verify Debt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtUpdatableFieldsEquals(Debt expected, Debt actual) {
        assertThat(actual)
            .as("Verify Debt relevant properties")
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a ->
                assertThat(a.getAmountPaid())
                    .as("check amountPaid")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountPaid())
            )
            .satisfies(a ->
                assertThat(a.getRemainingAmount())
                    .as("check remainingAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRemainingAmount())
            )
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebtUpdatableRelationshipsEquals(Debt expected, Debt actual) {
        assertThat(actual)
            .as("Verify Debt relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getSale()).as("check sale").isEqualTo(expected.getSale()));
    }
}
