package com.commercial.activities.domain;

import static com.commercial.activities.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StockArrivalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockArrivalAllPropertiesEquals(StockArrival expected, StockArrival actual) {
        assertStockArrivalAutoGeneratedPropertiesEquals(expected, actual);
        assertStockArrivalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockArrivalAllUpdatablePropertiesEquals(StockArrival expected, StockArrival actual) {
        assertStockArrivalUpdatableFieldsEquals(expected, actual);
        assertStockArrivalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockArrivalAutoGeneratedPropertiesEquals(StockArrival expected, StockArrival actual) {
        assertThat(actual)
            .as("Verify StockArrival auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockArrivalUpdatableFieldsEquals(StockArrival expected, StockArrival actual) {
        assertThat(actual)
            .as("Verify StockArrival relevant properties")
            .satisfies(a -> assertThat(a.getBarcode()).as("check barcode").isEqualTo(expected.getBarcode()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockArrivalUpdatableRelationshipsEquals(StockArrival expected, StockArrival actual) {
        assertThat(actual)
            .as("Verify StockArrival relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
